// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestFullAPIMVC.API.DAL;

#nullable disable

namespace RestFullAPIMVC.API.Migrations
{
    [DbContext(typeof(DbSistemaAcademicoContext))]
    [Migration("20260320012747_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAluno"), 1L, 1);

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdAluno")
                        .HasName("PK__Aluno__8092FCB33AC61EE7");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Boleto", b =>
                {
                    b.Property<int>("IdBoleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoleto"), 1L, 1);

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<int>("IdMatricula")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("('Pendente')");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdBoleto")
                        .HasName("PK__Boleto__362F6EA0D43CAA45");

                    b.HasIndex("IdMatricula");

                    b.ToTable("Boleto");
                });

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"), 1L, 1);

                    b.Property<int>("DuracaoSemestres")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCurso")
                        .HasName("PK__Curso__085F27D682F25C77");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Matricula", b =>
                {
                    b.Property<int>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatricula"), 1L, 1);

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("date");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("('Ativa')");

                    b.HasKey("IdMatricula")
                        .HasName("PK__Matricul__AD06C20FB86F020A");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdCurso");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Boleto", b =>
                {
                    b.HasOne("RestFullAPIMVC.API.Models.Matricula", "IdMatriculaNavigation")
                        .WithMany("Boletos")
                        .HasForeignKey("IdMatricula")
                        .IsRequired()
                        .HasConstraintName("FK__Boleto__IdMatric__412EB0B6");

                    b.Navigation("IdMatriculaNavigation");
                });

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Matricula", b =>
                {
                    b.HasOne("RestFullAPIMVC.API.Models.Aluno", "IdAlunoNavigation")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdAluno")
                        .IsRequired()
                        .HasConstraintName("FK__Matricula__IdAlu__3C69FB99");

                    b.HasOne("RestFullAPIMVC.API.Models.Curso", "IdCursoNavigation")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdCurso")
                        .IsRequired()
                        .HasConstraintName("FK__Matricula__IdCur__3D5E1FD2");

                    b.Navigation("IdAlunoNavigation");

                    b.Navigation("IdCursoNavigation");
                });

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Curso", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("RestFullAPIMVC.API.Models.Matricula", b =>
                {
                    b.Navigation("Boletos");
                });
#pragma warning restore 612, 618
        }
    }
}
